"""Route wiring helpers for ``server.py``.

This module keeps the dependency bundle selection for route registration in one
place so the Flask entrypoint does not carry several hundred lines of wiring.
"""

from routes.chat import register_chat_routes
from routes.operations import register_operation_routes
from routes.public import register_public_routes
from routes.users import register_user_routes


PUBLIC_ROUTE_KEYS = (
    "CSRF_TOKEN_TTL",
    "PUBLIC_DIR",
    "ROLE_LABEL",
    "SERVER_APP_NAME",
    "SERVER_RELEASE_ID",
    "SERVER_STARTED_AT",
    "SERVER_VERSION",
    "SESSION_COOKIE_SAMESITE",
    "SESSION_COOKIE_SECURE",
    "SESSION_TTL",
    "audit",
    "db_delete_session",
    "db_get_user_from_token",
    "db_save_session",
    "delete_csrf_token",
    "delete_csrf_tokens_for_username",
    "decrypt_field",
    "encrypt_field",
    "ensure_user_official_room_membership",
    "get_auth_db",
    "get_control_db",
    "get_client_ip",
    "get_current_user_ctx",
    "get_audit_db",
    "get_cached_system_setting",
    "get_db",
    "get_feature_settings",
    "get_member_level_rule",
    "get_server_output",
    "get_system_settings",
    "get_ua",
    "hash_password",
    "hash_token",
    "is_feature_enabled",
    "is_ip_blocked",
    "is_rate_limited",
    "json_resp",
    "make_csrf_token",
    "make_token",
    "normalize_text",
    "parse_birthdate",
    "points_service",
    "record_login_failure",
    "record_security_event",
    "require_csrf",
    "require_csrf_safe",
    "revoke_user_sessions",
    "score_password_strength",
    "store_csrf_token",
    "timing_delay",
    "validate_id_number",
    "validate_password",
    "enforce_password_strength",
    "validate_phone",
    "verify_csrf_double_submit",
    "verify_csrf_token",
    "verify_password",
)

CHAT_ROUTE_KEYS = (
    "CHAT_MESSAGE_MAX_LEN",
    "OFFICIAL_CHAT_ROOM_NAME",
    "add_violation",
    "append_chat_record",
    "audit",
    "check_user_rate_limit",
    "db_get_user_from_token",
    "db_get_user_role",
    "delete_csrf_token",
    "delete_csrf_tokens_for_username",
    "detect_chat_violation",
    "ensure_user_official_room_membership",
    "get_auth_db",
    "get_client_ip",
    "get_current_user_ctx",
    "get_audit_db",
    "get_db",
    "get_request_csrf_token",
    "get_ua",
    "get_member_level_rule",
    "is_feature_enabled",
    "json_resp",
    "normalize_text",
    "parse_positive_int",
    "require_csrf",
    "require_csrf_safe",
    "role_rank",
    "verify_csrf_token",
)

USER_ROUTE_KEYS = (
    "ACCOUNT_STATUSES",
    "MAX_MANAGERS",
    "MAX_EXTRA_SUPER_ADMINS",
    "MEMBER_LEVELS",
    "PASSWORD_HISTORY_LIMIT",
    "ROLE_LABEL",
    "ROLE_RANK",
    "add_violation",
    "audit",
    "check_user_rate_limit",
    "count_role",
    "db_get_user_from_token",
    "db_get_user_role",
    "delete_csrf_tokens_for_username",
    "decrypt_field",
    "encrypt_field",
    "ensure_user_official_room_membership",
    "get_auth_db",
    "get_readonly_auth_db",
    "get_client_ip",
    "get_current_user_ctx",
    "get_db",
    "get_ua",
    "hash_password",
    "hash_token",
    "is_feature_enabled",
    "json_resp",
    "normalize_text",
    "parse_birthdate",
    "parse_positive_int",
    "points_service",
    "revoke_user_sessions",
    "require_csrf",
    "require_csrf_safe",
    "SESSION_COOKIE_SAMESITE",
    "SESSION_COOKIE_SECURE",
    "enforce_password_strength",
    "score_password_strength",
    "role_rank",
    "get_member_level_rule",
    "get_system_settings",
    "STORAGE_DIR",
    "user_public_payload",
    "validate_id_number",
    "validate_password",
    "validate_phone",
    "verify_password",
)

OPERATION_ROUTE_KEYS = (
    "ANCHOR_DIR",
    "AUDIT_LOG_PATH",
    "BASE_DIR",
    "GIT_REPO_DIR",
    "CHAT_DIR",
    "chess_engine_store",
    "CURRENT_SERVER_BIND_STATE",
    "DB_DIR",
    "DB_PATH",
    "AUTH_DB_PATH",
    "AUDIT_DB_PATH",
    "CONTROL_DB_PATH",
    "STORAGE_CATALOG_DB_PATH",
    "POINTS_CHAIN_DB_PATH",
    "TRADING_DB_PATH",
    "FINANCE_DB_PATH",
    "JOBS_DB_PATH",
    "CHESS_ENGINE_DB_PATH",
    "LOG_DIR",
    "REPORTS_DIR",
    "RUNTIME_DIR",
    "SERVER_LOG_PATH",
    "SERVER_FILE_KEY_PATH",
    "STORAGE_DIR",
    "CERT_FILE",
    "KEY_FILE",
    "SESSION_COOKIE_SAMESITE",
    "SESSION_COOKIE_SECURE",
    "VIOLATION_APPEAL_WINDOW_HOURS",
    "activate_emergency_lockdown",
    "add_violation",
    "audit",
    "check_user_rate_limit",
    "detect_chat_violation",
    "fernet",
    "get_client_ip",
    "get_current_user_ctx",
    "get_audit_db",
    "get_db",
    "get_latest_violation",
    "get_feature_settings",
    "get_member_level_rule",
    "get_runtime_server_mode",
    "get_server_output",
    "get_system_settings",
    "get_ua",
    "is_audit_chain_enabled",
    "is_feature_enabled",
    "json_resp",
    "normalize_text",
    "parse_iso_to_datetime",
    "parse_positive_int",
    "points_service",
    "trading_service",
    "repair_audit_chain",
    "repair_violation_chains",
    "require_csrf",
    "require_csrf_safe",
    "revoke_user_sessions",
    "role_rank",
    "save_feature_settings",
    "save_settings",
    "secure_add_violation",
    "server_mode_service",
    "server_file_fernet",
    "snapshot_service",
    "integrity_guard",
    "verify_audit_integrity",
    "verify_violation_integrity",
)


def _pick(namespace, keys):
    return {key: namespace[key] for key in keys if key in namespace}


def register_server_routes(app, namespace):
    register_public_routes(app, _pick(namespace, PUBLIC_ROUTE_KEYS))
    register_chat_routes(app, _pick(namespace, CHAT_ROUTE_KEYS))
    register_user_routes(app, _pick(namespace, USER_ROUTE_KEYS))
    register_operation_routes(app, _pick(namespace, OPERATION_ROUTE_KEYS))
